"""
New bicarbonate generation by the kidney.

Source: Quantitative Human Physiology 3rd Edition
Unit 7: Renal Physiology
"""

from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation
)
from scripts.index import register_equation


def compute_new_bicarbonate(TA: float, NH4: float) -> float:
    """
    Calculate new bicarbonate generated per day.

    Each H+ secreted and excreted as TA or NH4+ generates one new HCO3-.

    Args:
        TA: Titratable acid excretion (mEq/day)
        NH4: Ammonium excretion (mEq/day)

    Returns:
        new_HCO3: New bicarbonate generated (mEq/day)
    """
    return TA + NH4


# Create equation
new_bicarbonate_generation = create_equation(
    id="renal.acid_base.new_bicarbonate_generation",
    name="New Bicarbonate Generation",
    category=EquationCategory.RENAL,
    latex=r"New\ HCO_3^- = TA + NH_4^+",
    simplified="New HCO3⁻ = TA + NH4⁺",
    description="New bicarbonate generated by kidney via titratable acid and ammonium excretion",
    compute_func=compute_new_bicarbonate,
    parameters=[
        Parameter(
            name="TA",
            description="Titratable acid excretion",
            units="mEq/day",
            symbol="TA",
            physiological_range=(10, 50)
        ),
        Parameter(
            name="NH4",
            description="Ammonium excretion",
            units="mEq/day",
            symbol="NH_4^+",
            physiological_range=(20, 80)
        )
    ],
    depends_on=[],
    metadata=EquationMetadata(
        source_unit=7,
        source_chapter="7.7"
    )
)

# Register equation
register_equation(new_bicarbonate_generation)
