"""Slow wave oscillation equation for GI smooth muscle."""

from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation
)
from scripts.index import register_equation
import numpy as np


def compute_slow_wave(t: float, V_rest: float = -60.0, A: float = 15.0, f: float = 0.05) -> float:
    """
    Calculate membrane potential during slow wave oscillation.

    Parameters
    ----------
    t : float
        Time (seconds)
    V_rest : float
        Resting membrane potential (mV), default -60 mV
    A : float
        Amplitude of oscillation (mV), default 15 mV
    f : float
        Frequency (Hz), default 0.05 Hz (3/min for stomach)

    Returns
    -------
    float
        Membrane potential (mV)
    """
    return V_rest + A * np.sin(2 * np.pi * f * t)


slow_wave = create_equation(
    id="gastrointestinal.motility.slow_wave",
    name="GI Slow Wave Oscillation",
    category=EquationCategory.GASTROINTESTINAL,
    latex=r"V(t) = V_{\text{rest}} + A \times \sin(2\pi f t)",
    simplified="V(t) = V_rest + A × sin(2πft)",
    description="Slow wave membrane potential oscillation generated by interstitial cells of Cajal (ICC)",
    compute_func=compute_slow_wave,
    parameters=[
        Parameter(
            name="t",
            description="Time",
            units="s",
            symbol="t",
            physiological_range=(0.0, 1000.0)
        ),
        Parameter(
            name="V_rest",
            description="Resting membrane potential",
            units="mV",
            symbol=r"V_{\text{rest}}",
            default_value=-60.0,
            physiological_range=(-70.0, -50.0)
        ),
        Parameter(
            name="A",
            description="Amplitude of oscillation",
            units="mV",
            symbol="A",
            default_value=15.0,
            physiological_range=(10.0, 20.0)
        ),
        Parameter(
            name="f",
            description="Frequency (stomach: 0.05-0.067 Hz, duodenum: 0.18-0.2 Hz, ileum: 0.13-0.15 Hz)",
            units="Hz",
            symbol="f",
            default_value=0.05,
            physiological_range=(0.03, 0.2)
        )
    ],
    metadata=EquationMetadata(
        source_unit=8,
        source_chapter="8.1"
    )
)

register_equation(slow_wave)
