"""Ontology data structures for schema generation."""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional


@dataclass
class OntologyNode:
    """Represents a node in the knowledge ontology."""

    id: str
    label: str
    node_type: str  # entity, concept, class, property
    depth: int
    stem: Optional[str] = None
    properties: Dict[str, Any] = field(default_factory=dict)
    inherited_properties: Dict[str, Any] = field(default_factory=dict)
    aliases: List[str] = field(default_factory=list)
    description: Optional[str] = None
    source_location: Optional[str] = None
    parent_id: Optional[str] = None
    children: List[str] = field(default_factory=list)

    def add_property(self, key: str, value: Any) -> None:
        """Add a property to this node."""
        self.properties[key] = value

    def inherit_property(self, key: str, value: Any, from_node: str) -> None:
        """Add an inherited property from an ancestor node."""
        if key not in self.properties:  # Don't override local properties
            self.inherited_properties[key] = {
                "value": value,
                "from": from_node
            }


@dataclass
class OntologyEdge:
    """Represents a relationship between ontology nodes."""

    source_id: str
    target_id: str
    edge_type: str  # parent_of, part_of, opposite_of, causes, related_to, etc.
    properties: Dict[str, Any] = field(default_factory=dict)
    strength: float = 1.0  # Confidence/weight (0.0-1.0)
    inferred: bool = False  # True if generated by Layer 3
    dimension: Optional[str] = None  # For multi-dimensional navigation

    def __post_init__(self):
        """Validate edge after initialization."""
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"Edge strength must be 0.0-1.0, got {self.strength}")


@dataclass
class Ontology:
    """Complete knowledge ontology with nodes, edges, and metadata."""

    nodes: Dict[str, OntologyNode] = field(default_factory=dict)
    edges: List[OntologyEdge] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    dimensions: List[str] = field(default_factory=list)

    def add_node(self, node: OntologyNode) -> None:
        """Add a node to the ontology."""
        self.nodes[node.id] = node

    def add_edge(self, edge: OntologyEdge) -> None:
        """Add an edge to the ontology."""
        # Validate edge references existing nodes
        if edge.source_id not in self.nodes:
            raise ValueError(f"Edge source '{edge.source_id}' not in ontology")
        if edge.target_id not in self.nodes:
            raise ValueError(f"Edge target '{edge.target_id}' not in ontology")
        self.edges.append(edge)

    def get_children(self, node_id: str) -> List[OntologyNode]:
        """Get all children of a node."""
        node = self.nodes.get(node_id)
        if not node:
            return []
        return [self.nodes[child_id] for child_id in node.children if child_id in self.nodes]

    def get_parent(self, node_id: str) -> Optional[OntologyNode]:
        """Get the parent of a node."""
        node = self.nodes.get(node_id)
        if not node or not node.parent_id:
            return None
        return self.nodes.get(node.parent_id)

    def get_ancestors(self, node_id: str) -> List[OntologyNode]:
        """Get all ancestors of a node (parent, grandparent, etc.)."""
        ancestors = []
        current = self.get_parent(node_id)
        while current:
            ancestors.append(current)
            current = self.get_parent(current.id)
        return ancestors

    def calculate_topology_score(self) -> float:
        """Calculate edge-to-node ratio (topology density)."""
        if len(self.nodes) == 0:
            return 0.0
        total_edges = len(self.edges)
        # Count hierarchical edges from parent-child relationships
        hierarchical_edges = sum(len(node.children) for node in self.nodes.values())
        return (total_edges + hierarchical_edges) / len(self.nodes)
