"""
Van't Hoff Osmotic Pressure - Osmotic pressure from solute concentration

Source: Quantitative Human Physiology 3rd Edition, Unit 2
"""
from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation, PHYSICAL_CONSTANTS
)
from scripts.index import register_equation
import numpy as np

def compute_osmotic_pressure(C: float, sigma: float = 1.0, R: float = 8.314, T_body: float = 310.0) -> float:
    """
    Calculate osmotic pressure using Van't Hoff equation.

    Formula: π = σ × C × RT

    Parameters:
    -----------
    C : float
        Solute concentration (mol/m³ or mM)
    sigma : float
        Reflection coefficient (0-1), default: 1.0
        σ=1 for ideal semipermeable membrane
        σ=0 for freely permeable
    R : float
        Gas constant (J/(mol·K)), default: 8.314
    T_body : float
        Body temperature (K), default: 310 K (37°C)

    Returns:
    --------
    pi : float
        Osmotic pressure (Pa if C in mol/m³)

    Typical values:
        Plasma osmolarity: ~290 mOsm/L → ~740 kPa (7.4 atm)
    """
    return sigma * C * R * T_body


# Create and register atomic equation
osmotic_pressure = create_equation(
    id="membrane.osmosis.osmotic_pressure",
    name="Van't Hoff Osmotic Pressure",
    category=EquationCategory.MEMBRANE,
    latex=r"\pi = \sigma \cdot C \cdot RT",
    simplified="pi = sigma * C * R * T",
    description="Osmotic pressure generated by solute concentration across a semipermeable membrane.",
    compute_func=compute_osmotic_pressure,
    parameters=[
        Parameter(
            name="C",
            description="Solute concentration",
            units="mol/m³",
            symbol="C",
            default_value=None,
            physiological_range=(0.0, 1000.0)  # mM
        ),
        Parameter(
            name="sigma",
            description="Reflection coefficient",
            units="dimensionless",
            symbol=r"\sigma",
            default_value=1.0,
            physiological_range=(0.0, 1.0)
        ),
        PHYSICAL_CONSTANTS["R"],
        PHYSICAL_CONSTANTS["T_body"],
    ],
    depends_on=[],
    metadata=EquationMetadata(source_unit=2, source_chapter="2.4")
)

register_equation(osmotic_pressure)
